version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.0
    volumes:
      - ./logstash/pipeline/example.conf:/usr/share/logstash/pipeline/example.conf

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.1.3
    user: root
    environment:
      ELASTICSEARCH_HOSTS: https://localhost:9200
      KIBANA_HOSTS: https://localhost:5601
    volumes:
      - ./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml"
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
      - /proc:/hostfs/proc
      - /:/hostfs

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
